fix link to Part 3
stac-api-extensions/filter pull request #19
Opened 2023-09-28 10:21 UTC by philvarner

**Related Issue(s):** 

- https://github.com/stac-api-extensions/filter/issues/13
- https://github.com/stac-api-extensions/filter/issues/7

**Proposed Changes:**

1. Fix links
2. Update text to current state of the world

**PR Checklist:**

- [X] This PR has **no** breaking changes.
- [X] I have added my changes to the [CHANGELOG](https://github.com/stac-api-extensions/filter/blob/main/CHANGELOG.md) **or** a CHANGELOG entry is not required.

2023-09-28 19:33 UTC, matthewhanson approved these changes, later dismissed

2023-09-28 19:54 UTC, m-mohr requested changes
See above

2023-09-28 19:54 UTC, m-mohr commented on README.md
> +<<<<<<< HEAD
This looks like an oversight

2023-09-28 20:41 UTC, philvarner commented on README.md
> +<<<<<<< HEAD
resolved.

2023-09-29 00:10 UTC, m-mohr approved these changes

2023-09-29 10:39 UTC, merged